New project page layout
piwheels/piwheels pull request #248
Opened 2020-08-16 17:08 UTC by bennuttall

Closes #241

TODO:

- [ ] Add tests
- [ ] Update db upgrade script

2020-08-23 20:56 UTC, bennuttall commented
@waveform80 this is complete now - would you mind giving it a review?

One thing I'd like to change is to move the file apt dependencies lookup into the project files query. I previously solved this in the previous json branch [using a join and string_agg](https://github.com/piwheels/piwheels/blob/json/piwheels/initdb/sql/create_piwheels.sql#L995:L999) but now we've introduced the [get_file_apt_dependencies](https://github.com/piwheels/piwheels/blob/241-project-page/piwheels/initdb/sql/create_piwheels.sql#L1513) function we need a way of aggregating the result of that function call into a single row OR moving the logic of that function into the project files query. What do you think?

2020-08-23 21:02 UTC, bennuttall commented
Oh the tests are failing on Travis because I'm trying to read the json file after writing. Doesn't look any different from the `packages.json` test though :/

2020-08-28 19:04 UTC, bennuttall commented
@waveform80 this is now ready for review

2020-09-19 21:50 UTC, waveform80 requested changes
Everything's minor *but* for that one bit in the scribe with explicit ABIs & code-names

2020-09-19 21:50 UTC, waveform80 commented on piwheels/master/the_scribe.py
> +        f['file_abi_tag'] == 'none' and abi > f['builder_abi']
Is this meant to be abi greater-than or abi greater-than-or-equal-to? The latter would *seem* to be what we want but maybe I'm missing something.

2020-09-19 21:50 UTC, waveform80 commented on piwheels/master/the_scribe.py
> +    def write_pages(self, package, both=False, exclude=None):
What happened to my keywords-only "*"? :)

2020-09-19 21:50 UTC, waveform80 commented on piwheels/master/the_scribe.py
> +            'releases': releases_dict,
Oh, I would've be soooo tempted to dict-comprehension releases_dict ;)

2020-09-19 21:50 UTC, waveform80 commented on piwheels/master/the_scribe.py
> +        canon_proj_dir = pkg_dir.with_name(canonicalize_name(pkg_dir.name))
These are redundant aren't they?

2020-09-19 21:50 UTC, waveform80 commented on piwheels/master/the_scribe.py
> +                    version.skip),
Urggggggh - hard-coded ABIs *and* release names. Surely there's a better way of doing this? I wouldn't mind this sort of stuff in the *templates* as ultimately they probably want to be configurable for an installation anyway, but having this hard-coded in the master itself .... urgh.

2020-09-20 03:46 UTC, bennuttall commented
[![](https://pbs.twimg.com/media/EiU3RF5WoAA4PJJ?format=jpg)](https://twitter.com/overflow_meme/status/1307512035278811138)

https://twitter.com/overflow_meme/status/1307512035278811138

2020-09-22 00:18 UTC, waveform80 approved these changes

2020-09-22 00:31 UTC, merged